import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>T3 App | Real </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className="text-brand1">Hello welcome to new t3 build</h1>
      </main>
    </>
  );
};

export default Home;

